version: '3.8'
services:
  ghproxy:
    image: oopsunix/ghproxy:latest
    # image：ghcr.io/oopsunix/ghproxy:latest
    # image: registry.cn-hangzhou.aliyuncs.com/oopsunix/ghproxy:latest
    container_name: ghproxy
    restart: unless-stopped
    volumes:
      - ./data:/app
    network_mode: host